package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tcollegian generated by hbm2java
 */
@Entity
@Table(name = "tcollegian", schema = "dbo", catalog = "scheduleDB"
)
public class Tcollegian implements java.io.Serializable {

    private int id;
    private Teducationgroup teducationgroup;
    private String name;
    private Integer enteryear;
    private String description;
    private Date dto;
    private Set<Tweekschedule> tweekschedules = new HashSet<Tweekschedule>(0);

    public Tcollegian() {
    }

    public Tcollegian(int id, Teducationgroup teducationgroup, String name) {
        this.id = id;
        this.teducationgroup = teducationgroup;
        this.name = name;
    }

    public Tcollegian(int id, Teducationgroup teducationgroup, String name, Integer enteryear, String description, Date dto, Set<Tweekschedule> tweekschedules) {
        this.id = id;
        this.teducationgroup = teducationgroup;
        this.name = name;
        this.enteryear = enteryear;
        this.description = description;
        this.dto = dto;
        this.tweekschedules = tweekschedules;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "groupid", nullable = false)
    public Teducationgroup getTeducationgroup() {
        return this.teducationgroup;
    }

    public void setTeducationgroup(Teducationgroup teducationgroup) {
        this.teducationgroup = teducationgroup;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "enteryear")
    public Integer getEnteryear() {
        return this.enteryear;
    }

    public void setEnteryear(Integer enteryear) {
        this.enteryear = enteryear;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dto", length = 10)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tcollegian")
    public Set<Tweekschedule> getTweekschedules() {
        return this.tweekschedules;
    }

    public void setTweekschedules(Set<Tweekschedule> tweekschedules) {
        this.tweekschedules = tweekschedules;
    }

}
