package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teducationgroup generated by hbm2java
 */
@Entity
@Table(name = "teducationgroup", schema = "dbo", catalog = "scheduleDB"
)
public class Teducationgroup implements java.io.Serializable {

    private int id;
    private String symbol;
    private String name;
    private String description;
    private Date dto;
    private Set<Tprofessor> tprofessors = new HashSet<Tprofessor>(0);
    private Set<Tlesson> tlessons = new HashSet<Tlesson>(0);
    private Set<Tcollegian> tcollegians = new HashSet<Tcollegian>(0);
    private Set<TroomGroup> troomGroups = new HashSet<TroomGroup>(0);

    public Teducationgroup() {
    }

    public Teducationgroup(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Teducationgroup(int id, String symbol, String name, String description, Date dto, Set<Tprofessor> tprofessors, Set<Tlesson> tlessons, Set<Tcollegian> tcollegians, Set<TroomGroup> troomGroups) {
        this.id = id;
        this.symbol = symbol;
        this.name = name;
        this.description = description;
        this.dto = dto;
        this.tprofessors = tprofessors;
        this.tlessons = tlessons;
        this.tcollegians = tcollegians;
        this.troomGroups = troomGroups;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "symbol")
    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dto", length = 10)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teducationgroup")
    public Set<Tprofessor> getTprofessors() {
        return this.tprofessors;
    }

    public void setTprofessors(Set<Tprofessor> tprofessors) {
        this.tprofessors = tprofessors;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teducationgroup")
    public Set<Tlesson> getTlessons() {
        return this.tlessons;
    }

    public void setTlessons(Set<Tlesson> tlessons) {
        this.tlessons = tlessons;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teducationgroup")
    public Set<Tcollegian> getTcollegians() {
        return this.tcollegians;
    }

    public void setTcollegians(Set<Tcollegian> tcollegians) {
        this.tcollegians = tcollegians;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teducationgroup")
    public Set<TroomGroup> getTroomGroups() {
        return this.troomGroups;
    }

    public void setTroomGroups(Set<TroomGroup> troomGroups) {
        this.troomGroups = troomGroups;
    }

}
