package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tlesson generated by hbm2java
 */
@Entity
@Table(name = "tlesson", schema = "dbo", catalog = "scheduleDB"
)
public class Tlesson implements java.io.Serializable {

    private int id;
    private Teducationgroup teducationgroup;
    private String symbol;
    private String name;
    private String gender;
    private String lessontype;
    private Integer unit;
    private Date dto;
    private Set<TprofLesson> tprofLessons = new HashSet<TprofLesson>(0);

    public Tlesson() {
    }

    public Tlesson(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Tlesson(int id, Teducationgroup teducationgroup, String symbol, String name, String gender, String lessontype, Integer unit, Date dto, Set<TprofLesson> tprofLessons) {
        this.id = id;
        this.teducationgroup = teducationgroup;
        this.symbol = symbol;
        this.name = name;
        this.gender = gender;
        this.lessontype = lessontype;
        this.unit = unit;
        this.dto = dto;
        this.tprofLessons = tprofLessons;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "groupid")
    public Teducationgroup getTeducationgroup() {
        return this.teducationgroup;
    }

    public void setTeducationgroup(Teducationgroup teducationgroup) {
        this.teducationgroup = teducationgroup;
    }

    @Column(name = "symbol")
    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "gender")
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "lessontype")
    public String getLessontype() {
        return this.lessontype;
    }

    public void setLessontype(String lessontype) {
        this.lessontype = lessontype;
    }

    @Column(name = "unit")
    public Integer getUnit() {
        return this.unit;
    }

    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dto", length = 10)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tlesson")
    public Set<TprofLesson> getTprofLessons() {
        return this.tprofLessons;
    }

    public void setTprofLessons(Set<TprofLesson> tprofLessons) {
        this.tprofLessons = tprofLessons;
    }

}
