package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TprofLesson generated by hbm2java
 */
@Entity
@Table(name = "tprofLesson", schema = "dbo", catalog = "scheduleDB"
)
public class TprofLesson implements java.io.Serializable {

    private int id;
    private Tlesson tlesson;
    private Tprofessor tprofessor;
    private Set<Tweekschedule> tweekschedules = new HashSet<Tweekschedule>(0);

    public TprofLesson() {
    }

    public TprofLesson(int id, Tlesson tlesson, Tprofessor tprofessor) {
        this.id = id;
        this.tlesson = tlesson;
        this.tprofessor = tprofessor;
    }

    public TprofLesson(int id, Tlesson tlesson, Tprofessor tprofessor, Set<Tweekschedule> tweekschedules) {
        this.id = id;
        this.tlesson = tlesson;
        this.tprofessor = tprofessor;
        this.tweekschedules = tweekschedules;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "lessonid", nullable = false)
    public Tlesson getTlesson() {
        return this.tlesson;
    }

    public void setTlesson(Tlesson tlesson) {
        this.tlesson = tlesson;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "profid", nullable = false)
    public Tprofessor getTprofessor() {
        return this.tprofessor;
    }

    public void setTprofessor(Tprofessor tprofessor) {
        this.tprofessor = tprofessor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tprofLesson")
    public Set<Tweekschedule> getTweekschedules() {
        return this.tweekschedules;
    }

    public void setTweekschedules(Set<Tweekschedule> tweekschedules) {
        this.tweekschedules = tweekschedules;
    }

}
