package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TroomGroup generated by hbm2java
 */
@Entity
@Table(name = "troomGroup", schema = "dbo", catalog = "scheduleDB"
)
public class TroomGroup implements java.io.Serializable {

    private int id;
    private Teducationgroup teducationgroup;
    private Troom troom;
    private String type;
    private int timeslot;
    private int daynum;

    public TroomGroup() {
    }

    public TroomGroup(int id, Teducationgroup teducationgroup, Troom troom, String type, int timeslot, int daynum) {
        this.id = id;
        this.teducationgroup = teducationgroup;
        this.troom = troom;
        this.type = type;
        this.timeslot = timeslot;
        this.daynum = daynum;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "groupid", nullable = false)
    public Teducationgroup getTeducationgroup() {
        return this.teducationgroup;
    }

    public void setTeducationgroup(Teducationgroup teducationgroup) {
        this.teducationgroup = teducationgroup;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "roomid", nullable = false)
    public Troom getTroom() {
        return this.troom;
    }

    public void setTroom(Troom troom) {
        this.troom = troom;
    }

    @Column(name = "type", nullable = false)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "timeslot", nullable = false)
    public int getTimeslot() {
        return this.timeslot;
    }

    public void setTimeslot(int timeslot) {
        this.timeslot = timeslot;
    }

    @Column(name = "daynum", nullable = false)
    public int getDaynum() {
        return this.daynum;
    }

    public void setDaynum(int daynum) {
        this.daynum = daynum;
    }

}
