package entity;
// Generated Dec 28, 2016 2:25:13 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tweekschedule generated by hbm2java
 */
@Entity
@Table(name = "tweekschedule", schema = "dbo", catalog = "scheduleDB"
)
public class Tweekschedule implements java.io.Serializable {

    private int id;
    private Tcollegian tcollegian;
    private TprofLesson tprofLesson;
    private Troom troom;
    private Integer daynum;
    private Integer timeslotnum;
    private String weektype;
    private Integer examday;
    private Integer examtime;
    private Date dto;
    private Date creationdate;
    private Date editedin;
    private String lessontype;

    public Tweekschedule() {
    }

    public Tweekschedule(int id, Tcollegian tcollegian, TprofLesson tprofLesson) {
        this.id = id;
        this.tcollegian = tcollegian;
        this.tprofLesson = tprofLesson;
    }

    public Tweekschedule(int id, Tcollegian tcollegian, TprofLesson tprofLesson, Troom troom, Integer daynum, Integer timeslotnum, String weektype, Integer examday, Integer examtime, Date dto, Date creationdate, Date editedin) {
        this.id = id;
        this.tcollegian = tcollegian;
        this.tprofLesson = tprofLesson;
        this.troom = troom;
        this.daynum = daynum;
        this.timeslotnum = timeslotnum;
        this.weektype = weektype;
        this.examday = examday;
        this.examtime = examtime;
        this.dto = dto;
        this.creationdate = creationdate;
        this.editedin = editedin;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "collegianid")
    public Tcollegian getTcollegian() {
        return this.tcollegian;
    }

    public void setTcollegian(Tcollegian tcollegian) {
        this.tcollegian = tcollegian;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "proflessonid", nullable = false)
    public TprofLesson getTprofLesson() {
        return this.tprofLesson;
    }

    public void setTprofLesson(TprofLesson tprofLesson) {
        this.tprofLesson = tprofLesson;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "roomid")
    public Troom getTroom() {
        return this.troom;
    }

    public void setTroom(Troom troom) {
        this.troom = troom;
    }

    @Column(name = "daynum")
    public Integer getDaynum() {
        return this.daynum;
    }

    public void setDaynum(Integer daynum) {
        this.daynum = daynum;
    }

    @Column(name = "timeslotnum")
    public Integer getTimeslotnum() {
        return this.timeslotnum;
    }

    public void setTimeslotnum(Integer timeslotnum) {
        this.timeslotnum = timeslotnum;
    }

    @Column(name = "weektype")
    public String getWeektype() {
        return this.weektype;
    }

    public void setWeektype(String weektype) {
        this.weektype = weektype;
    }

    @Column(name = "examday")
    public Integer getExamday() {
        return this.examday;
    }

    public void setExamday(Integer examday) {
        this.examday = examday;
    }

    @Column(name = "examtime")
    public Integer getExamtime() {
        return this.examtime;
    }

    public void setExamtime(Integer examtime) {
        this.examtime = examtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dto", length = 10)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "creationdate", length = 10)
    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "editedin", length = 10)
    public Date getEditedin() {
        return this.editedin;
    }

    public void setEditedin(Date editedin) {
        this.editedin = editedin;
    }
    
    @Column(name = "lessontype", nullable = false)
    public String getLessontype() {
        return this.lessontype;
    }

    public void setLessontype(String lessontype) {
        this.lessontype = lessontype;
    }

}
